// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewBook(arg1:string):Promise<void>;

export function FillGuardAndCaramel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ResetProducts():Promise<void>;

export function SelectBook():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function StartFill(arg1:string):Promise<Array<string>>;
