// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth(arg1) {
  return window['go']['main']['App']['Auth'](arg1);
}

export function CreateNewBook(arg1) {
  return window['go']['main']['App']['CreateNewBook'](arg1);
}

export function FillGuardAndCaramel(arg1, arg2, arg3) {
  return window['go']['main']['App']['FillGuardAndCaramel'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetProducts() {
  return window['go']['main']['App']['ResetProducts']();
}

export function SelectBook() {
  return window['go']['main']['App']['SelectBook']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StartFill(arg1) {
  return window['go']['main']['App']['StartFill'](arg1);
}

export function StartInventory() {
  return window['go']['main']['App']['StartInventory']();
}
